### PR TITLE
Bucket Support

### PR DESCRIPTION
**Pull request by hunterwilliams**
work in progress but putting here for discussion/more easily viewable

### CODE REVIEW

**Comment by hunterwilliams** [comment]
Looking into fixing the tuples issue next but don't think that'd really make sense without a 3d chart..

* Currently tuples in a chart is not supported correct? I see them being loaded into the chart, but not getting them to plot correctly with the default options. Assume it requires a Z axis $frequency 
* Are there constraints that would show up with the cooccurence call that wouldn't be a facet? I assume so, but want to check

**Comment by grtjn** [comment]
Tuples, as in pairs of two values + frequency, can be shown reasonably well with a 2d bubbles chart. Color might also work. Triples and larger will need more dimensions..

I expect users to want to show some data as facet, some data as chart, some data in a map, etc.. Usually having such data shown in only one of these. But if all could be driven by facet response, then it could also be a matter of suppressing/selecting (exlude/include) display of certain facets in a particular presentation.

Wouldn't worry about that too much now though..

**Comment by grtjn** [comment]
Glanced over the PR. Would it make sense to try to decouple this directive and mlsearch(ctrl) a bit? It looks like it is looping over all facets automatically, showing all with same chart config. I was actually expecting it to just show one chart for a particular given facet or values endpoint. It is now also making backend calls itself, while if you feed it with facet data, that is usually already around. You could feed the directive with `ctrl.search.facets`. The current setup gives limited flexibility.

This kind of goes beyond this PR perhaps, but maybe you could work towards this? Perhaps try taking `facets` instead of `mlSearchController`, and making `mlSearch` optional?

**Comment by hunterwilliams** [comment]
@grtjn these would be some questions for @ryanjdew

**Comment by hunterwilliams** [comment]
Also doesn't look like this currently supports bubble charts.

**Comment by grtjn** [comment]
Check if highcharts-more is loaded..

**Comment by hunterwilliams** [comment]
Meant more that mlhighcharts doesn't currently have any functionality to support it as far as I can tell. I mean I can add it just not currently there

**Comment by grtjn** [comment]
Bubble chart is not really different. It is just a different chart type. But, you need to make sure highcharts-more.js is loaded, otherwise it won't render..

**Comment by grtjn** [comment]
Finally found time for a proper look at this. I totally missed the fact you refer to facts from the chartConfig. That gives you full control. And no values definitions needed, those are generated on the spot. Pretty flexible actually!

**Comment by hunterwilliams** [comment]
So I added bubble charts easily (literally just type bubble in config) however the Z value is not ascertained at all currently even when not using buckets (this is just how the code works unless @ryanjdew has something I'm missing there). 

When using buckets I'd have to rebucket all the values - painful but doable - do we have any solution for that at the moment?

**Comment by grtjn** [comment]
Leverage /v1/search to get bucketed facet values, instead of calling /v1/values?

**Comment by hunterwilliams** [comment]
That's what I'm using but I can't it won't work for two values because it's needs/ is currently calling the coocurrence endpoint?

**Comment by grtjn** [comment]
Ah yes, there is no such thing as bucketed tuples to my knowledge..

But not everything uses tuples. You can do a simple value-$frequency chart too, just disable `xAxisCategoriesMLConstraint`..

**Comment by hunterwilliams** [comment]
Cool then I'll ignore bucketed tuples

**Comment by grtjn** [comment]
Opened a separate ticket #6 for bubble charts specifically. I leave it up to @hunterwilliams to include it in this PR or not..

**Comment by ryanjdew** [comment]
Sorry it has taken me some time to get to this. This looks good. I really like how the mlsearch controller is being used. Perhaps we can do something a little more to determine whether to use the facets for bucketed results and the /v1/values for the values so we can set specific result sizes beyond the facet limit? Also, I would like to adjust it the so both ways use the controller instead of mlSearch like I was. @hunterwilliams, would you like to make those adjustments? Or I can merge this and build off of this.

**Comment by hunterwilliams** [comment]
Maybe merge and then can make more issues on project? Mostly so not making a lot of changes in the one Pr. May be able to split some tasks too. Also I didn't update the tests for this piece.

**Comment by hunterwilliams** [comment]
Also my only hesitation is may need to consult @joemfb to make sure not heading into potential zone of deprecation or vast changes

**Comment by grtjn** [comment]
Fix for #2

**Pull request merged**
